/*
 * generated by Xtext
 */
package com.collins.trustedsystems.briefcase.json;

import com.collins.trustedsystems.briefcase.json.JsonStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class JsonStandaloneSetup extends JsonStandaloneSetupGenerated{

	public static void doSetup() {
		new JsonStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

