/*
 * generated by Xtext
 */
package com.collins.trustedsystems.briefcase.json;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JsonRuntimeModule extends com.collins.trustedsystems.briefcase.json.AbstractJsonRuntimeModule {

}
