/*
 * generated by Xtext
 */
package com.collins.trustedsystems.briefcase.json.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JsonUiModule extends com.collins.trustedsystems.briefcase.json.ui.AbstractJsonUiModule {
	public JsonUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
