/*
 * generated by Xtext
 */
package com.collins.trustedsystems.briefcase.json.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractJsonJavaValidator extends org.osate.xtext.aadl2.properties.validation.PropertiesJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.collins.trustedsystems.briefcase.json.json.JsonPackage.eINSTANCE);
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://aadl.info/AADL/2.0"));
		return result;
	}

}
