/*
 * generated by Xtext
 */
package com.collins.trustedsystems.briefcase.json.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JsonAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/collins/trustedsystems/briefcase/json/parser/antlr/internal/InternalJsonParser.tokens");
	}
}
