/*
 * generated by Xtext
 */
package com.collins.trustedsystems.briefcase.json.serializer;

import com.collins.trustedsystems.briefcase.json.serializer.AbstractJsonSyntacticSequencer;

public class JsonSyntacticSequencer extends AbstractJsonSyntacticSequencer {
}
