/*
 * generated by Xtext
 */
package com.collins.trustedsystems.briefcase.json.serializer;

import com.collins.trustedsystems.briefcase.json.serializer.AbstractJsonSemanticSequencer;

public class JsonSemanticSequencer extends AbstractJsonSemanticSequencer {
}
