/*
 * generated by Xtext
 */
package com.collins.trustedsystems.briefcase.json.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class JsonProposalProvider extends com.collins.trustedsystems.briefcase.json.ui.contentassist.AbstractJsonProposalProvider {

}
