/*
 * generated by Xtext
 */
package com.collins.trustedsystems.briefcase.json.validation;

/**
 * This class contains custom validation rules.
 * @deprecated
 * This class is replaced by the {@link JsonValidator} class and will be removed in 1.0.0.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@Deprecated
public class JsonJavaValidator extends JsonValidator {

}
